### ISSUE TITLE
Limited number of fields exported.

### ISSUE THREAD

**Issue by ghost** [gedl/gc-csv#2]
Hi. Just tried your tool out as it's exactly what I'm after. All worked OK except it's only exported the following fields:
"Name","Number 1","Number 2","Email"

I'm not sure if this is a restriction of the API or the tool. My contacts have other fields. eg. address, it would be great if these could be exported as well. Cheers.

**Comment by gedl** [comment]
Hi @CarrotCruncher 

Apologies for the late reply. I hadn't noticed somebody was actually trying to use this.

The tool does indeed support a subset of the existing fields. This is because there is no straightforward way to access the whole data in a generic way and therefore this is done on a field-by-field basis.

I have released a new version (https://github.com/gedl/gc-csv/releases/tag/0.0.9) that supports extracting the Postal Address. Also note that you can extract multiple phone numbers if you repeat the field name on your mapping. The same is valid for e-mail addresses and Postal Addresses. This does not apply to the name of the contact.

**Example:** 

```
java -jar gc-csv-0.0.9.jar  -C <REDACTED>.apps.googleusercontent.com -S <REDACTED> -d /tmp/gc-csv -p --output-header "Nome" "Tel 1"  "Tel 2"  "Morada" --output-mapping NAME PHONE_NUMBER PHONE_NUMBER ADDRESS
```

will extract the following fields from your contact list:
- Contact name
- First telephone number
- Second telephone number
- First Address

Remember to add `-p` to the command if you want to see the results on the console output or `-f` if you want to write the output to a file.

I guess you don't have a ICW1000 Voip phone, but if you did you could also use `--icw1000` to send the contacts to the device.

I will close this issue now, please do reopen if you can't get this to work, or if you'd like an additional field to be extracted.

**Comment by ghost** [comment]
Dear Gonçalo Luiz,

The email sent to mail@carrotcruncher.tk with subject
"Re: [gedl/gc-csv] Limited number of fields exported. (#2)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to mail@carrotcruncher.tk, you will not receive a delivery
notification again.

TK MAILIAS

---

Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
